CREATE TYPE "review_category" AS ENUM (
  'UNIVERSITY',
  'FACULTY',
  'TEACHER',
  'COURSE',
  'COURSE_OFFERING'
);

CREATE TABLE "universities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "city" varchar,
  "website" varchar,
  "created_at" timestamp
);

CREATE TABLE "allowed_email_domains" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "university_id" integer NOT NULL,
  "domain" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "faculties" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "university_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "departments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "faculty_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "teachers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "department_id" integer NOT NULL,
  "full_name" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "department_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "code" varchar,
  "created_at" timestamp
);

CREATE TABLE "course_offerings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" integer NOT NULL,
  "faculty_id" integer,
  "semester" varchar,
  "year" integer,
  "created_at" timestamp
);

CREATE TABLE "course_offering_teachers" (
  "course_offering_id" integer NOT NULL,
  "teacher_id" integer NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "university_id" integer NOT NULL,
  "user_key" varchar UNIQUE NOT NULL,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "magic_link_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "email" varchar,
  "token" varchar UNIQUE NOT NULL,
  "expires_at" timestamp,
  "used_at" timestamp,
  "created_at" timestamp
);

CREATE TABLE "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" review_category NOT NULL,
  "university_id" integer,
  "faculty_id" integer,
  "teacher_id" integer,
  "course_id" integer,
  "course_offering_id" integer,
  "rating_overall" smallint,
  "ratings_json" text,
  "body" text,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "abuse_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "review_id" integer NOT NULL,
  "reporter_user_id" integer,
  "reason_code" varchar,
  "details" text,
  "status" varchar,
  "created_at" timestamp
);

CREATE UNIQUE INDEX "uq_uni_domain" ON "allowed_email_domains" ("university_id", "domain");

CREATE INDEX "idx_offerings_course_term" ON "course_offerings" ("course_id", "year", "semester");

CREATE UNIQUE INDEX "uq_offering_teacher" ON "course_offering_teachers" ("course_offering_id", "teacher_id");

CREATE INDEX "idx_cot_teacher" ON "course_offering_teachers" ("teacher_id");

CREATE INDEX "idx_reviews_university" ON "reviews" ("university_id");

CREATE INDEX "idx_reviews_faculty" ON "reviews" ("faculty_id");

CREATE INDEX "idx_reviews_teacher" ON "reviews" ("teacher_id");

CREATE INDEX "idx_reviews_course" ON "reviews" ("course_id");

CREATE INDEX "idx_reviews_course_offering" ON "reviews" ("course_offering_id");

CREATE INDEX "idx_reviews_created_at" ON "reviews" ("created_at");

COMMENT ON COLUMN "users"."user_key" IS 'pseudonymous key (salted hash of email)';

COMMENT ON COLUMN "magic_link_tokens"."user_id" IS 'nullable until confirmed';

COMMENT ON COLUMN "magic_link_tokens"."email" IS 'store hashed/encrypted if possible';

COMMENT ON COLUMN "reviews"."ratings_json" IS 'structured per-criterion ratings as JSON';

COMMENT ON COLUMN "reviews"."body" IS 'review text';

COMMENT ON COLUMN "abuse_reports"."reporter_user_id" IS 'nullable — allow anonymous reports';

ALTER TABLE "allowed_email_domains" ADD FOREIGN KEY ("university_id") REFERENCES "universities" ("id");

ALTER TABLE "faculties" ADD FOREIGN KEY ("university_id") REFERENCES "universities" ("id");

ALTER TABLE "departments" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculties" ("id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "course_offerings" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "course_offerings" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculties" ("id");

ALTER TABLE "course_offering_teachers" ADD FOREIGN KEY ("course_offering_id") REFERENCES "course_offerings" ("id");

ALTER TABLE "course_offering_teachers" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("university_id") REFERENCES "universities" ("id");

ALTER TABLE "magic_link_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("university_id") REFERENCES "universities" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculties" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("course_offering_id") REFERENCES "course_offerings" ("id");

ALTER TABLE "abuse_reports" ADD FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");

ALTER TABLE "abuse_reports" ADD FOREIGN KEY ("reporter_user_id") REFERENCES "users" ("id");
