@startuml
!theme plain
left to right direction

actor "Гість" as guest
actor "Студент" as student
actor "Абітурієнт" as applicant
actor "Адміністратор" as admin

applicant --|> guest
student --|> guest

rectangle "Система університетських відгуків і соціальної взаємодії" {

    package "Відгуки" {
        usecase "Читати усі відгуки" as readReviews
        usecase "Залишати відгуки" as createReview
        usecase "Редагувати свій відгук" as editReview
        usecase "Видалити свій відгук" as deleteReview
        usecase "Лайкнути / дизлайкнути відгук" as rateReview
        usecase "Поскаржитись на відгук" as reportReview
        usecase "Модерувати відгуки" as moderateReviews
    }

    package "Міні соцмережа для студентів" {
        usecase "Оприлюднити пост" as createPost
        usecase "Редагувати свій пост" as editPost
        usecase "Видалити свій пост" as deletePost
        usecase "Лайкнути / дизлайкнути пост" as ratePost
        usecase "Залишати коментарі під постами" as createComment
        usecase "Лайкнути / дизлайкнути коментар" as rateComment
        usecase "Поскаржитись на пост" as reportPost
        usecase "Створювати опитування для студентів" as createPoll
        usecase "Голосувати в опитуванні" as vote
    }

    package "Сервіс для абітурієнтів" {
        usecase "Читати інформацію про університети" as readUniversities
        usecase "Порівнювати університети" as compareEntities
        usecase "Підібрати університет за критеріями" as getUniversityRecommendations
        usecase "Адмініструвати інформацію про університети" as moderateUniversityInfo
    }
}

guest --> readReviews
student --> createReview
student --> editReview
student --> deleteReview
applicant --> rateReview
student --> rateReview
admin --> moderateReviews
student --> reportReview
applicant --> reportReview

student --> createPost
student --> editPost
student --> deletePost
student --> createComment
student --> vote
student --> rateComment
student --> ratePost
student --> reportPost
admin --> createPoll

guest --> readUniversities
applicant --> compareEntities
applicant --> getUniversityRecommendations
admin --> moderateUniversityInfo

@enduml
